version: '3.7'
x-default-opts:
  &default-opts
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
services:
  redis:
    image: redis
    hostname: redis.server
    command: [
      "redis-server",
      "--appendonly yes",
    ]
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=false"
    environment:
      - 'TZ=Africa/Johannesburg'
    networks:
      haakco-net:
        aliases:
          - redis.server
    ports:
      - '6379:6379'
    volumes:
      - 'db_haak_redis:/data'
  rediscommander:
    image: rediscommander/redis-commander:latest
    hostname: rediscommander.server
    environment:
      - 'TZ=Africa/Johannesburg'
      - 'REDIS_HOSTS=haakco:redis.server:6379'
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - 'traefik.enable=true'
        - "traefik.http.routers.rediscommander.rule=Host(`rediscommander.${ADMIN_DOMAIN}`)"
        - "traefik.http.routers.rediscommander.entrypoints=websecure"
        - "traefik.http.services.rediscommander.loadbalancer.server.port=8081"
        - "traefik.http.routers.rediscommander.tls=true"
        - "traefik.http.routers.rediscommander.middlewares=rediscommanderauth"
        - "traefik.http.middlewares.rediscommanderauth.basicauth.users=haakco:$$apr1$$nzSK8fmx$$ZJLXWY7EyMCwgYZNpF/Gz/"
    networks:
      haakco-net:
        aliases:
          - rediscommander.server
      traefik-net:
        aliases:
          - rediscommander.server
networks:
  haakco-net:
    attachable: true
    external: true
    driver: overlay
  traefik-net:
    attachable: true
    external: true
    driver: overlay
volumes:
  db_haak_redis:
    external: false
    name: db_haak_redis
